spring:
  datasource:
    url: jdbc:mysql://49.234.85.17:3306/data-integration-system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456789
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: 49.234.85.17 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: 123456789 # Redis服务器连接密码
    timeout: 300ms # 连接超时时间（毫秒）

logging:
  level:
    root: info
    com.softline: debug

logstash:
  host: 49.234.85.17